import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useNavigate, Link } from 'react-router-dom';
import Button from '../components/ui/Button';
import Loading from '../components/ui/Loading';
import Card from '../components/ui/Card';
import PageLayout from '../components/layouts/PageLayout';
import { ArrowLeft } from 'lucide-react';

const defaultFormData = {
  name: '',
  type: '',
  dev_partner: '',
  grant_amount: '',
  loan_amount: '',
  counterpart_funding: '',
  disbursement: '',
  non_grant_instrument: ''
};

const FundingSourceFormPage = ({
  mode = 'add',
  initialFormData = defaultFormData,
  isLoading: isLoadingProp = false,
  onSubmit: onSubmitProp,
  error,
  pageTitle,
  pageSubtitle
}) => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const [formData, setFormData] = useState(initialFormData);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setFormData(initialFormData);
  }, [initialFormData]);

  const handleLogout = () => {
    logout();
    navigate('/admin/login');
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    if (onSubmitProp) {
      await onSubmitProp(formData, setIsLoading);
      return;
    }
    try {
      await new Promise(resolve => setTimeout(resolve, 1000));
      const sourceData = {
        ...formData,
        grant_amount: parseFloat(formData.grant_amount) || 0,
        loan_amount: parseFloat(formData.loan_amount) || 0,
        counterpart_funding: parseFloat(formData.counterpart_funding) || 0,
        disbursement: parseFloat(formData.disbursement) || 0,
        non_grant_instrument: formData.non_grant_instrument || null
      };
      if (mode === 'add') {
        // In a real app, the ID would be generated by the backend
        console.log('Created funding source:', sourceData);
      } else {
        console.log('Updated funding source:', sourceData);
      }
      
      // Check if user came from project form
      const projectFormData = localStorage.getItem('projectFormData');
      if (projectFormData) {
        // Navigate back to project form instead of admin funding sources list
        navigate('/admin/projects/new');
      } else {
        navigate('/admin/funding-sources');
      }
    } catch (error) {
      console.error('Error saving funding source:', error);
    } finally {
      setIsLoading(false);
    }
  };

  if (error) {
    return (
      <PageLayout bgColor="bg-gray-50">
        <Card padding={true}>
          <div className="text-center py-10">
            <h2 className="text-xl font-semibold text-gray-800 mb-2">{error}</h2>
            <p className="text-gray-600 mb-6">The funding source you are looking for does not exist or has been removed.</p>
            <Button 
              onClick={() => navigate('/admin/funding-sources')}
              className="bg-purple-600 hover:bg-purple-700 text-white"
            >
              Return to Funding Sources
            </Button>
          </div>
        </Card>
      </PageLayout>
    );
  }

  return (
    <PageLayout bgColor="bg-gray-50">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:justify-between md:items-center mb-6">
        <div className="flex items-center space-x-4">
          <Link to="/admin/funding-sources" className="text-purple-600 hover:text-purple-700 transition-colors duration-200">
            <ArrowLeft className="w-6 h-6" />
          </Link>
          <div>
            <h2 className="text-2xl font-bold text-gray-800">{pageTitle || (mode === 'add' ? 'Add New Funding Source' : 'Edit Funding Source')}</h2>
            <p className="text-gray-500">{pageSubtitle || (mode === 'add' ? 'Create a new funding source for climate projects' : 'Update funding source information')}</p>
          </div>
        </div>
        <div className="flex items-center space-x-4 mt-4 md:mt-0">
          <div className="text-right">
            <p className="text-sm font-medium text-gray-900">{user?.fullName}</p>
            <p className="text-xs text-gray-500">{user?.role}</p>
          </div>
          <Button onClick={handleLogout} variant="outline" size="sm">
            Logout
          </Button>
        </div>
      </div>
      {/* Form Card */}
      <Card hover padding={true}>
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* First Row - Name (full width) */}
          <div>
            <label className="block text-sm font-medium text-gray-700">Name *</label>
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleInputChange}
              className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200"
              required
              placeholder="e.g., Green Climate Fund"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700">Type</label>
              <input
                type="text"
                name="type"
                value={formData.type}
                onChange={handleInputChange}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200"
                placeholder="e.g., Multilateral, Bilateral, Private"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">Development Partner *</label>
              <input
                type="text"
                name="dev_partner"
                value={formData.dev_partner}
                onChange={handleInputChange}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200"
                required
                placeholder="e.g., World Bank"
              />
            </div>
          </div>

          {/* Third Row onwards - Financial fields */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-700">Grant Amount (USD)</label>
              <input
                type="number"
                name="grant_amount"
                value={formData.grant_amount}
                onChange={handleInputChange}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200"
                step="0.01"
                min="0"
                placeholder="0.00"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">Loan Amount (USD)</label>
              <input
                type="number"
                name="loan_amount"
                value={formData.loan_amount}
                onChange={handleInputChange}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200"
                step="0.01"
                min="0"
                placeholder="0.00"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">Counterpart Funding (USD)</label>
              <input
                type="number"
                name="counterpart_funding"
                value={formData.counterpart_funding}
                onChange={handleInputChange}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200"
                step="0.01"
                min="0"
                placeholder="0.00"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">Disbursement (USD)</label>
              <input
                type="number"
                name="disbursement"
                value={formData.disbursement}
                onChange={handleInputChange}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200"
                step="0.01"
                min="0"
                placeholder="0.00"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">Non-Grant Instrument</label>
              <input
                type="text"
                name="non_grant_instrument"
                value={formData.non_grant_instrument}
                onChange={handleInputChange}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200"
                placeholder="e.g., Concessional Loan, Technical Assistance"
              />
            </div>
          </div>
          {/* Form Actions */}
          <div className="flex justify-end space-x-3 pt-6 border-t">
            <Button
              type="button"
              onClick={() => navigate('/admin/funding-sources')}
              variant="outline"
              disabled={isLoading}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              className="bg-purple-600 hover:bg-purple-700 text-white hover:shadow-lg hover:shadow-purple-200 transition-all duration-200"
              disabled={isLoading}
            >
              {isLoading 
                ? (mode === 'add' ? 'Creating...' : 'Updating...') 
                : (mode === 'add' ? 'Create Funding Source' : 'Update Funding Source')
              }
            </Button>
          </div>
        </form>
      </Card>
    </PageLayout>
  );
};

export default FundingSourceFormPage;
